### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by fr0nkk** [WD40andTape/MatlabRenderer#1]
Hello and thank you for this neat toolbox, implementing everything purely in matlab is impressive!

I noticed the performance limitations you faced and wanted to offer some insights.

The backstory is I needed to display and work on large 3D datasets but matlab's built-in visualization tools can get really slow when there is too much to display. So I found a way to use OpenGL directly from matlab without dependencies other than undocumented stuff and published it. Here is the [OpenGL access toolbox](https://www.mathworks.com/matlabcentral/fileexchange/102109-access-opengl-from-matlab) and the [visualization toolbox](https://www.mathworks.com/matlabcentral/fileexchange/132892-fast-visualization). The key really was to use OpenGL to make the large 3D computations. With this strategy, it is possible to render multi-million faces meshes at full resolution fluidly.

If you ever want to make use of the OpenGL access toolbox to achieve almost real time performance at full resolution, I would be happy to help make it happen.

Cheers!

**Comment by WD40andTape** [comment]
Hi @fr0nkk. Thanks for your kind comments, and really great work on your own toolboxes! Fantastic to have those available for performance-critical visualizations! All the best, George.
